### ISSUE TITLE
Handling embedded structs - should probably allow shorter name?

### ISSUE THREAD

**Issue by dolzenko** [vrischmann/envconfig#16]
Hi! Thanks for this useful tool. I have minor suggestion (happy to do PR as well). Currently this fails

``` go
package main

import (
    "fmt"
    "os"

    "github.com/vrischmann/envconfig"
)

type OtherConfig struct {
    Address string
}

type Config struct {
    OtherConfig
}

func main() {
    os.Setenv("CONFIG_ADDRESS", "example.com")
    var conf struct {
        Config
    }
    if err := envconfig.Init(&conf); err != nil {
        fmt.Printf("err=%s\n", err)
    }
}
```

with 

```
err=envconfig: keys CONFIG_OTHERCONFIG_ADDRESS, CONFIG_OTHER_CONFIG_ADDRESS, config_other_config_address, config_otherconfig_address not found
```

I think it should be reasonable to include `CONFIG_ADDRESS` in env var names searched. This is also inline with Go semantics where you can write embedded fields without specifying full path, e.g. 

```
    conf.Config.Address = "123"
    conf.Config.OtherConfig.Address = "123"
```

both work.

WDYT?

**Comment by vrischmann** [comment]
Hi.

Thanks for the suggestion. I never embed my structs, usually because I use the name of the field as a namespace, but I agree with you, it would be nice to handle this case correctly.

I'd love a PR !

**Comment by khyew** [comment]
Sorry for commenting on a closed issue but this piqued my interest and I was wondering: how would you handle conflicts? As far as I know, this is legal Go code:

```
type Config struct {
  Name string
  InnerConfig
}

type InnerConfig struct {
  Name string
  Type int
}
```

would the env var `CONFIG_NAME` set the `Name` property of the `Config` struct or the embedded `InnerConfig` struct's property?

**Comment by khyew** [comment]
EDIT: after playing around, it appears that the named property `Name` of the `Config` struct shadows that of the embedded `InnerConfig` struct's similarly-named property. If this feature were to be implemented in envconfig, I believe it should behave the same way.

**Comment by vrischmann** [comment]
Thanks for your input @khyew . I almost never use embedded struct and especially not with envconfig but yeah it makes sense to me that Config.name should shadow the InnerConfig.

I have no time to implement handling embedded struct correctly myself but if someone is interested I'd be happy to review and merge a PR for this.
