### ISSUE TITLE
[Feature Request] default tag support for slices

### ISSUE THREAD

**Issue by GrigoriyMikhalkin** [vrischmann/envconfig#19]
Currently `default` tag is unsupported on slices. As it explained [here](https://github.com/vrischmann/envconfig/blob/98b0b9a570bdd3eb00e3e6eeb15548e7f982bfd3/envconfig.go#L25):

> The `default` tag is unsupported on slices because slice parsing uses , as the separator, as does the envconfig tags separator.

What I propose is to change `default` tag to support following format:

    default=value1;value2;etc

If this value will be applied to slice, it will be split by `;`. If applied to string, value is applied as is. Else, it will panic. I would gladly implement this feature.

**Comment by vrischmann** [comment]
Hi,

I guess that could work yes. I'd be happy to review your PR.
