### ISSUE TITLE
Tag new release from master

### ISSUE THREAD

**Issue by ajanata** [vrischmann/envconfig#23]
If this project truly is "done", could you please tag a new release now that #20 has been merged? This is making for some awkward dependency management on our end. Thanks.

**Comment by vrischmann** [comment]
Sure, I didn't realize the last tag was so behind. I'll do it this week end probably.

**Comment by vrischmann** [comment]
Hi, I just tagged v1.2.0.

**Comment by ajanata** [comment]
Awesome, thank you!
