### ISSUE TITLE
Default empty string

### ISSUE THREAD

**Issue by franpog859** [vrischmann/envconfig#24]
Is there a possibility to set default empty string? Something like this:
```go
type config struct {
   Something string `envconfig:"default="`
}
```

**Comment by vrischmann** [comment]
Hi,

you can just use `optional` instead:

```go
type config struct {
   Something string `envconfig:"optional"`
}
```

since the zero-value of a string is the empty string it will work just fine.

**Comment by franpog859** [comment]
Thanks a lot! It works perfectly 🎉
