### ISSUE TITLE
Slices are cleared and appended, should be overwritten

### ISSUE THREAD

**Issue by pavelbazika** [vrischmann/envconfig#27]
Hi

I've a scenario, where at first configuration `struct` is loaded from config file and then envconfig is applied to overwrite some settings from environment variables, when they exist.

One of the fields in the config struct is a slice of `string`. When an environment variable for this slice exists, the slice is not replaced by value from the environment variable. Instead, resulting slice contains as many items as it was in config file set to empty string followed by environment variable value.

For example:
- original slice value from config file - `["foo"]`
- environment variable value - `"bar"`
- slice after envconfig - `["", "bar"]`

I guess the bug is in function `setSliceField` on line https://github.com/vrischmann/envconfig/blob/e689cc56e3bd23fb94f1caea0a526c60cfff085c/envconfig.go#L252

There shouldn't be  `value.Len()` but `0` in my opinion.

Best Regards

Pavel

**Comment by vrischmann** [comment]
Hi,

can you make a small test case which reproduces the problem ?

Also since you seem to have an idea of where the problem is I'd be happy to review and merge a PR.

**Comment by pavelbazika** [comment]
#28
